get_profile:
    path:     /user/{id}
    methods:  [GET]
    defaults: { _controller: 'Javiern\Controller\UserProfile::getProfile' }

edit_profile:
    path:     /user/{id}
    methods:  [POST]
    defaults: { _controller: 'Javiern\Controller\UserProfile::edit' }

create_profile:
    path:     /user
    methods:  [POST]
    defaults: { _controller: 'Javiern\Controller\UserProfile::createProfile' }

delete_profile:
    path:     /user/{id}
    methods:  [DELETE]
    defaults: { _controller: 'Javiern\Controller\UserProfile::remove' }

add_picture:
    path:     /user/{id}/picture
    methods:  [POST]
    defaults: { _controller: 'Javiern\Controller\UserProfile::addPicture' }