parameters:
  db.connection:
    url: sqlite://%kernel.resources_dir%/db.sqlite
    driver: pdo_sqlite
    path: %kernel.resources_dir%/db.sqlite

services:

  db-config:
    class: Doctrine\DBAL\Configuration

  db:
    class: Doctrine\DBAL\DriverManager
    factory: ['Doctrine\DBAL\DriverManager', getConnection]
    arguments: [%db.connection%, "@db-config"]

  event-dispatcher:
    class: Symfony\Component\EventDispatcher\EventDispatcher
    calls:
      - [ addSubscriber, ["@router-listener"] ]
      - [ addListener, [kernel.exception, ["@exception-listener", onKernelException]] ]

  exception-listener:
    class: Javiern\EventListener\ExceptionListener

  controller-resolver:
    class: Javiern\Controller\ControllerResolver
    arguments: [ "@service_container" ]
  request-stack:
    class: Symfony\Component\HttpFoundation\RequestStack
  argument-resolver:
    class: Symfony\Component\HttpKernel\Controller\ArgumentResolver

  http-kernel:
    class: Symfony\Component\HttpKernel\HttpKernel
    arguments:
      - "@event-dispatcher"
      - "@controller-resolver"
      - "@request-stack"
      - "@argument-resolver"

  router-locator:
    class: Symfony\Component\Config\FileLocator
    arguments:
      - %kernel.resources_dir%
  router-yaml-loader:
    class: Symfony\Component\Routing\Loader\YamlFileLoader
    arguments:
      - "@router-locator"
  router-request-context:
    class: Symfony\Component\Routing\RequestContext
  router:
    class: Symfony\Component\Routing\Router
    arguments:
      - "@router-yaml-loader"
      - routes.yml
      - cache_dir: %kernel.cache_dir%
      - "@router-request-context"
  router-listener:
    class: Symfony\Component\HttpKernel\EventListener\RouterListener
    arguments:
      - "@router"
      - "@request-stack"

  user-profile-dao:
    class: Javiern\DAO\UserProfile
    arguments:
      -  "@db"

  validator:
      class: Symfony\Component\Validator\Validation
      factory: ['Symfony\Component\Validator\Validation', createValidator]

  user-profile-validator:
    class: Javiern\Services\UserProfileValidationService
    arguments:
      - "@validator"

  olx-cdn-api:
    class: GuzzleHttp\Client
    arguments:
      - base_uri: https://api.olx.com/v1.0/
      - timeout: 120
